apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "noriswim.fullname" . }}
  labels:
    {{- include "noriswim.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "noriswim.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "noriswim.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: {{ printf "%s:%s" .Values.image.repository .Values.image.tag | quote }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}